name: obs_status
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # logging
  logging: ^1.2.0
  logging_appenders: ^1.2.0+1

  # Web
  flutter_web_plugins:
    sdk: flutter

    # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1


  # router
  go_router: ^13.2.0


  # riverpod
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  freezed_annotation: ^2.4.1


  # Utils
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.9


flutter:
  generate: true

  uses-material-design: true



